# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          runtime: node@22
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Fix lint errors
        run: pnpm lint --fix

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef # 551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
