# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: lts/-1
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Fix lint errors
        run: pnpm lint --fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
